In [1]:
from sklearn.ensemble import GradientBoostingClassifier  
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score
from sklearn import metrics                         
from sklearn.model_selection import GridSearchCV
import pandas as pd

In [2]:
#Read the train file:
file=pd.read_csv("dataset.csv")
print(file.head())

   Age  Attrition     BusinessTravel  DailyRate              Department  \
0   41          1      Travel_Rarely       1102                   Sales
1   49          0  Travel_Frequently        279  Research & Development
2   37          1      Travel_Rarely       1373  Research & Development
3   33          0  Travel_Frequently       1392  Research & Development
4   27          0      Travel_Rarely        591  Research & Development

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1
1                 8          1  Life Sciences              1               2
2                 2          2          Other              1               4
3                 3          4  Life Sciences              1               5
4                 2          1        Medical              1               7

  ...  RelationshipSatisfaction StockOptionLevel  TotalWorkingYears  \
0 ...                         1                0                  8
1 ...                         4                1                 10
2 ...                         2                0                  7
3 ...                         3                0                  8
4 ...                         4                1                  6

   TrainingTimesLastYear  WorkLifeBalance YearsAtCompany  YearsInCurrentRole  \
0                      0                1              6                   4
1                      3                3             10                   7
2                      3                3              0                   0
3                      3                3              8                   7
4                      3                3              2                   2

  YearsSinceLastPromotion  YearsWithCurrManager  ID
0                       0                     5   0
1                       1                     7   1
2                       0                     0   2
3                       3                     0   3
4                       2                     2   4

[5 rows x 34 columns]

In [3]:
#Remove the unneccessary features and target variable

a1=file.drop("Attrition",axis=1)
a2=a1.drop("EmployeeCount",axis=1)
a3=a2.drop("EmployeeNumber",axis=1)
a4=a3.drop("ID",axis=1)

#Convert the categorical features into numerical ones

df = pd.get_dummies(a4) 
#print(df)

      Age  DailyRate  DistanceFromHome  Education  EnvironmentSatisfaction  \
0      41       1102                 1          2                        2
1      49        279                 8          1                        3
2      37       1373                 2          2                        4
3      33       1392                 3          4                        4
4      27        591                 2          1                        1
5      32       1005                 2          2                        4
6      59       1324                 3          3                        3
7      30       1358                24          1                        4
8      38        216                23          3                        4
9      36       1299                27          3                        3
10     35        809                16          3                        1
11     29        153                15          2                        4
12     31        670                26          1                        1
13     34       1346                19          2                        2
14     28        103                24          3                        3
15     29       1389                21          4                        2
16     32        334                 5          2                        1
17     22       1123                16          2                        4
18     53       1219                 2          4                        1
19     38        371                 2          3                        4
20     24        673                11          2                        1
21     36       1218                 9          4                        3
22     34        419                 7          4                        1
23     21        391                15          2                        3
24     34        699                 6          1                        2
25     53       1282                 5          3                        3
26     32       1125                16          1                        2
27     42        691                 8          4                        3
28     44        477                 7          4                        1
29     46        705                 2          4                        2
...   ...        ...               ...        ...                      ...
998    26        683                 2          1                        1
999    42       1147                10          3                        3
1000   52        258                 8          4                        3
1001   37       1462                11          3                        1
1002   35        200                18          2                        3
1003   25        949                 1          3                        1
1004   26        652                 7          3                        3
1005   29        332                17          3                        2
1006   49       1475                28          2                        1
1007   29        337                14          1                        3
1008   54        971                 1          3                        4
1009   58       1055                 1          3                        4
1010   55       1136                 1          4                        2
1011   36       1174                 3          4                        1
1012   31        667                 1          4                        2
1013   30        855                 7          4                        4
1014   31        182                 8          5                        1
1015   34        560                 1          4                        4
1016   31        202                 8          3                        1
1017   27       1377                11          1                        2
1018   36        172                 4          4                        1
1019   36        329                16          4                        3
1020   47        465                 1          3                        1
1021   25        383                 9          2                        1
1022   37       1413                 5          2                        3
1023   56       1255                 1          2                        1
1024   47        359                 2          4                        1
1025   24       1476                 4          1                        4
1026   32        601                 7          5                        4
1027   34        401                 1          3                        4

      HourlyRate  JobInvolvement  JobLevel  JobSatisfaction  MonthlyIncome  \
0             94               3         2                4           5993
1             61               2         2                2           5130
2             92               2         1                3           2090
3             56               3         1                3           2909
4             40               3         1                2           3468
5             79               3         1                4           3068
6             81               4         1                1           2670
7             67               3         1                3           2693
8             44               2         3                3           9526
9             94               3         2                3           5237
10            84               4         1                2           2426
11            49               2         2                3           4193
12            31               3         1                3           2911
13            93               3         1                4           2661
14            50               2         1                3           2028
15            51               4         3                1           9980
16            80               4         1                2           3298
17            96               4         1                4           2935
18            78               2         4                4          15427
19            45               3         1                4           3944
20            96               4         2                3           4011
21            82               2         1                1           3407
22            53               3         3                2          11994
23            96               3         1                4           1232
24            83               3         1                1           2960
25            58               3         5                3          19094
26            72               1         1                1           3919
27            48               3         2                2           6825
28            42               2         3                4          10248
29            83               3         5                1          18947
...          ...             ...       ...              ...            ...
998           36               2         1                4           3904
999           31               3         4                1          16799
1000          54               3         1                1           2950
1001          94               3         1                3           3629
1002          60               3         3                4           9362
1003          81               3         1                4           3229
1004         100               4         1                1           3578
1005          51               2         3                1           7988
1006          97               2         2                1           4284
1007          84               3         3                4           7553
1008          54               3         4                4          17328
1009          76               3         5                1          19701
1010          81               4         4                4          14732
1011          99               3         2                2           9278
1012          50               1         1                3           1359
1013          73               3         2                1           4779
1014          93               3         4                2          16422
1015          91               3         1                1           2996
1016          34               2         1                2           1261
1017          91               3         1                1           2099
1018          37               2         2                4           5810
1019          98               2         2                1           5647
1020          74               3         1                4           3420
1021          68               2         1                1           4400
1022          84               4         1                3           3500
1023          90               3         1                1           2066
1024          82               3         4                3          17169
1025          42               3         2                3           4162
1026          97               3         2                4           9204
1027          86               2         1                2           3294

          ...       JobRole_Manufacturing Director  JobRole_Research Director  \
0         ...                                    0                          0
1         ...                                    0                          0
2         ...                                    0                          0
3         ...                                    0                          0
4         ...                                    0                          0
5         ...                                    0                          0
6         ...                                    0                          0
7         ...                                    0                          0
8         ...                                    1                          0
9         ...                                    0                          0
10        ...                                    0                          0
11        ...                                    0                          0
12        ...                                    0                          0
13        ...                                    0                          0
14        ...                                    0                          0
15        ...                                    1                          0
16        ...                                    0                          0
17        ...                                    0                          0
18        ...                                    0                          0
19        ...                                    0                          0
20        ...                                    1                          0
21        ...                                    0                          0
22        ...                                    0                          1
23        ...                                    0                          0
24        ...                                    0                          0
25        ...                                    0                          0
26        ...                                    0                          0
27        ...                                    0                          0
28        ...                                    0                          0
29        ...                                    0                          0
...       ...                                  ...                        ...
998       ...                                    0                          0
999       ...                                    0                          0
1000      ...                                    0                          0
1001      ...                                    0                          0
1002      ...                                    1                          0
1003      ...                                    0                          0
1004      ...                                    0                          0
1005      ...                                    0                          0
1006      ...                                    0                          0
1007      ...                                    0                          0
1008      ...                                    0                          1
1009      ...                                    0                          1
1010      ...                                    0                          1
1011      ...                                    0                          0
1012      ...                                    0                          0
1013      ...                                    0                          0
1014      ...                                    0                          1
1015      ...                                    0                          0
1016      ...                                    0                          0
1017      ...                                    0                          0
1018      ...                                    0                          0
1019      ...                                    0                          0
1020      ...                                    0                          0
1021      ...                                    0                          0
1022      ...                                    0                          0
1023      ...                                    0                          0
1024      ...                                    0                          1
1025      ...                                    0                          0
1026      ...                                    0                          0
1027      ...                                    0                          0

      JobRole_Research Scientist  JobRole_Sales Executive  \
0                              0                        1
1                              1                        0
2                              0                        0
3                              1                        0
4                              0                        0
5                              0                        0
6                              0                        0
7                              0                        0
8                              0                        0
9                              0                        0
10                             0                        0
11                             0                        0
12                             1                        0
13                             0                        0
14                             0                        0
15                             0                        0
16                             1                        0
17                             0                        0
18                             0                        0
19                             1                        0
20                             0                        0
21                             0                        0
22                             0                        0
23                             1                        0
24                             1                        0
25                             0                        0
26                             1                        0
27                             0                        1
28                             0                        0
29                             0                        0
...                          ...                      ...
998                            1                        0
999                            0                        0
1000                           0                        0
1001                           0                        0
1002                           0                        0
1003                           0                        0
1004                           0                        0
1005                           0                        0
1006                           0                        0
1007                           0                        0
1008                           0                        0
1009                           0                        0
1010                           0                        0
1011                           0                        1
1012                           0                        0
1013                           0                        1
1014                           0                        0
1015                           1                        0
1016                           1                        0
1017                           0                        0
1018                           0                        0
1019                           0                        1
1020                           1                        0
1021                           0                        0
1022                           0                        0
1023                           1                        0
1024                           0                        0
1025                           0                        1
1026                           0                        1
1027                           0                        0

      JobRole_Sales Representative  MaritalStatus_Divorced  \
0                                0                       0
1                                0                       0
2                                0                       0
3                                0                       0
4                                0                       0
5                                0                       0
6                                0                       0
7                                0                       1
8                                0                       0
9                                0                       0
10                               0                       0
11                               0                       0
12                               0                       1
13                               0                       1
14                               0                       0
15                               0                       1
16                               0                       1
17                               0                       1
18                               0                       0
19                               0                       0
20                               0                       1
21                               1                       0
22                               0                       0
23                               0                       0
24                               0                       0
25                               0                       1
26                               0                       0
27                               0                       0
28                               0                       0
29                               0                       0
...                            ...                     ...
998                              0                       0
999                              0                       0
1000                             0                       0
1001                             0                       0
1002                             0                       0
1003                             0                       0

In [4]:
from sklearn import svm
clf = svm.SVC(C=.001,gamma=100,kernel="rbf")
clf.fit(df[0:801],file.Attrition[0:801])

SVC(C=0.001, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=100, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [5]:
from sklearn.metrics import accuracy_score
v=clf.predict(df[801:])
print(accuracy_score(v,file.Attrition[801:]))

0.8414096916299559